---
title: "Staircase and elevator use"
author: "Nandor Hajdu"
date: "2023-01-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, warning = FALSE,
                      message = FALSE)
```

```{r read_data}
library(tidyverse)
library(tidymodels)
library(janitor)
library(glmertree)
library(here)
library(parameters)

# Set up parallel processing
doParallel::registerDoParallel(cores = parallelly::availableCores())

theme_set(theme_light())

```


```{r read_data}
stairs_raw <- read_csv(here("data/behav.csv"))

stairs <-
  stairs_raw %>%
  clean_names() %>%
  filter(building_visited != "Egyéb:") %>%
  mutate(id = as.factor(id),
         choice = as.factor(choice)) %>%
  # filter IDs with less than 8 entries
  group_by(id) %>%
  add_count() %>%
  ungroup() %>%
  filter(n >= 8) %>% 
  select(-n)

```

## Split data into training and test sets

```{r}

set.seed(12)

stairs_split <- group_initial_split(stairs, group = id)
stairs_train <- training(stairs_split)
stairs_test <- testing(stairs_split)

```


## Specify tidymodels recipe of feature engineering

```{r glmertree_recipe}

stairs_rec <- 
  recipe(stairs_train, formula = choice ~ .) %>%
  step_impute_mode(peers) %>% 
  step_string2factor(all_nominal_predictors()) %>% 
  step_impute_knn(health) %>% 
  step_scale(all_numeric_predictors()) %>% 
  step_zv(all_predictors())
  
print(stairs_rec)

```

## Execute the recipe and prepare the data for analysis

```{r recipe_prep}
rec_prepped <- prep(stairs_rec)
stairs_train_baked <- bake(rec_prepped, new_data = NULL)

glimpse(stairs_train_baked)

```

# Model fitting

```{r model_fitting, cache=TRUE}
stairs_res <-
  glmertree(
    choice ~ 1 | id | laziness + fatigue + luggage +
      elevator_speed + environmental_consciousness +
      temperature + appeal +
      number_of_people_waiting_for_the_elevator + peers +
      health + building_visited + speed +
      destination_floor,
    family = "binomial",
    data = stairs_train_baked
  )


# write_rds(stairs_res, file = here("model/stairs_res.rds"))
# stairs_res <- read_rds(file = here("model/stairs_res.rds"))
```

# Checking model performance

```{r accuracy_metrics}

model_pred_tbl <- 
  tibble(
    truth = stairs_train_baked$choice,
    stairs_prob = predict(stairs_res)
  )

model_roc_auc <- 
  roc_auc(model_pred_tbl, truth, stairs_prob, event_level = "second")[[1,3]]

stairs_test_baked <- bake(rec_prepped, new_data = stairs_test)

glmertree_pred <- 
  predict(
        stairs_res,
        newdata = stairs_test_baked,
        type = "response",
        allow.new.levels = TRUE
  )

predictions <- 
  tibble(
    truth = stairs_test_baked$choice,
    stairs_prob = 1 - glmertree_pred,
    elevator_prob = glmertree_pred,
    pred = as.factor(if_else(glmertree_pred > 0.5, 1, 0))
    )

predictions %>% 
  conf_mat(truth, pred) %>% 
  autoplot("heatmap")

accuracy_metrics <- 
  bind_rows(
    accuracy(predictions, truth = truth, estimate = pred),
    sensitivity(predictions, truth = truth, estimate = pred),
    specificity(predictions, truth = truth, estimate = pred),
    precision(predictions, truth = truth, estimate = pred),
    recall(predictions, truth = truth, estimate = pred),
    bal_accuracy(predictions, truth, pred),
    kap(predictions, truth = truth, estimate = pred),
    f_meas(predictions, truth, pred),
    roc_auc(predictions, truth, stairs_prob),
    pr_auc(predictions, truth, stairs_prob)
  ) %>% 
  mutate(.estimate = signif(.estimate, 3),
         .estimator = NULL
  )

accuracy_metrics

roc_curve(predictions, truth, stairs_prob) %>% autoplot()
pr_curve(predictions, truth, stairs_prob) %>% autoplot()

```

# Investigating variable importance
```{r}

tbl_colnames <- names(select(stairs, -c(id, choice)))
tbl <- tibble(!!!tbl_colnames, .rows = 0)
permutation_n <- 100

mean_aucs <- 
  tibble(
    variable = tbl_colnames,
    perm_aucs = list(Inf),
    perm_mean_auc = c(Inf)
)

for (col in names(tbl)){
  
  roc_aucs <- c()
  
  for (i in 1:permutation_n){

    perm_df <- stairs_train_baked
    perm_df[, eval(parse(text = col))] <- perm_df[sample(1:nrow(perm_df)), eval(parse(text = col))]
    
    shuffled_pred <- 
  predict(
        stairs_res,
        newdata = perm_df,
        type = "response",
        allow.new.levels = TRUE
  )
    
    predictions <- 
  tibble(
    truth = stairs_train_baked$choice,
    stairs_prob = 1 - shuffled_pred
  )
    roc_aucs <- append(roc_aucs, roc_auc(predictions, truth, stairs_prob)[[1,3]])
  }
  
  mean_aucs[[match(col, names(tbl)), 2]][[1]] <- roc_aucs
  mean_aucs[[match(col, names(tbl)), 3]] <- mean(roc_aucs)
  
  }

mean_aucs <- mean_aucs %>% 
  mutate(
   importance = model_roc_auc - perm_mean_auc 
  )
  
mean_aucs %>% 
  mutate(variable = fct_reorder(variable, importance)) %>% 
  ggplot() +
  aes(y = variable, x = importance) +
  geom_bar(stat = "identity")+
  labs(y = NULL, x = "Variable importance")

```


